### ISSUE TITLE
hbase 0.98 isn't working

### ISSUE THREAD

**Issue by colmex** [HariSekhon/Dockerfiles#13]
the 0.98 image for hbase isn't working. 
This is the command I run to start the container:
`docker run -ti -p 2181:2181 -p 8080:8080 -p 8085:8085 -p 9090:9090 -p 9095:9095 -p 16000:16000 -p 16010:16010 -p 16201:16201 -p 16301:16301 harisekhon/hbase:0.98`

then when it starts I try to create a namespace with `create_namespace 'crawler'` I get the following error:
```
hbase(main):001:0> create_namespace 'crawler'
2017-08-22 19:03:57,379 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

ERROR: java.io.IOException
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2247)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:104)
        at org.apache.hadoop.hbase.ipc.FifoRpcScheduler$1.run(FifoRpcScheduler.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.apache.hadoop.hbase.master.HMaster.createNamespace(HMaster.java:3524)
        at org.apache.hadoop.hbase.master.HMaster.createNamespace(HMaster.java:3430)
        at org.apache.hadoop.hbase.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java:44958)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2195)
        ... 7 more

Here is some help for this command:
Create namespace; pass namespace name,
and optionally a dictionary of namespace configuration.
Examples:

  hbase> create_namespace 'ns1'
  hbase> create_namespace 'ns1', {'PROPERTY_NAME'=>'PROPERTY_VALUE'}


hbase(main):002:0>
```

**Comment by HariSekhon** [comment]
This appears to be caused by the Regionserver not starting up properly due to dependence on SSH, HBase 1.0 works regardless but 0.98 doesn't even though the builds are identical other than the `HBASE_VERSION` variable in the Dockerfiles :-/

It's late here so I'll look in to this more tomorrow if time permits.

**Comment by HariSekhon** [comment]
For now you could just pull `harisekhon/hbase:1.0` or newer instead.

**Comment by HariSekhon** [comment]
@colmex

I've just pushed a fix for older versions of HBase to work around its startup scripts being broken without SSH.

There is a newer `hbase:0.98` image with the fix available for you to use now.

Thanks for raising this issue by the way, please let me know if this resolves it for you.

Cheers

Hari

**Comment by colmex** [comment]
@HariSekhon awesome! thanks so much!

Just FYI I needed the `0.98` image because the major hbase library for python (happybase) only supports up to `0.98`. https://happybase.readthedocs.io/

**Comment by HariSekhon** [comment]
I'm actually using that library with the newer versions of HBase and use the Docker images from this repo for the dockerized tests... so I know it actually works.

You can check out the [Advanced Nagios Plugins Collection](https://github.com/HariSekhon/nagios-plugins) and [PyTools](https://github.com/HariSekhon/pytools) repos for many generic useful programs for HBase using that library including data generators, data skew analyzers and testing code.

The programs are found at the top level of those repos and the HBase tests using these different HBase versions are found here:

https://github.com/HariSekhon/nagios-plugins/blob/master/tests/test_hbase.sh

https://github.com/HariSekhon/pytools/blob/master/tests/test_hbase.sh

**Comment by colmex** [comment]
Interesting! I'm not using it directly, I'm frontera ( https://github.com/scrapinghub/frontera ) and the crawls stopped working when I upgraded to the most recent version it broke and I've only been able to get it running once I used hbase `0.98`.
