### ISSUE TITLE
hbase:dock-compose up does not work

### ISSUE THREAD

**Issue by lujiefsi** [HariSekhon/Dockerfiles#50]
in the hbase dir, run sudo dock-compose up,

zookeeper gives :

Got user-level KeeperException when processing sessionid:0x100000d1c840001 type:setData cxid:0x41 zxid:0x22 txntype:-1 reqpath:n/a Error Path:/hbase/meta-region-server Error:KeeperErrorCode = NoNode for /hbase/meta-region-server

HMaster gives:

hbase-master_1        | 2021-11-06 02:29:51,523 WARN  [ProcExecTimeout] assignment.AssignmentManager: STUCK Region-In-Transition rit=OPENING, location=hbase_hbase-regionserver_1.hbase_default,16020,1636165658608, table=hbase:namespace, region=8bd53a267bdd63e7157795522f5cb0a4

hbase shell:

hbase(main):001:0> list_namespace
NAMESPACE                                                                       

ERROR: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2977)
	at org.apache.hadoop.hbase.master.HMaster.getNamespaces(HMaster.java:3273)
	at org.apache.hadoop.hbase.master.MasterRpcServices.listNamespaceDescriptors(MasterRpcServices.java:1233)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:324)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:304)

For usage try 'help "list_namespace"'

**Comment by alexanderkranga** [comment]
This is still an issue in 2024
